import { eventTags } from "./eventTags";

export interface Action {
    readonly action: () => void; //TODO: Add proper parameters
}

export const addEvent: Action = {
    action: () => {
        console.log("Adding event");
    }
}

export const addTasks: Action = {
    action: () => {
        console.log("Adding tasks");
    }
}

//Turn each of these into an array generated by eventTags[]
export const tags: Action[] = eventTags.map((tag) => {
    return {
        action: () => {
            console.log("Tagging " + tag.name);
        }
    }
});